'use client';

import React, { useState, useEffect, useMemo } from 'react';
import { createClient } from '@/lib/supabase/client';
import { useOrganization } from '@/context/OrganizationContext';
import { useLanguage } from '@/lib/LanguageContext';
import toast from 'react-hot-toast';
import { 
  CheckSquare, Plus, Play, Check, Edit, Trash2, Clock, 
  AlertTriangle, Link2, User, FileText, Sparkles, RefreshCw, 
  SlidersHorizontal, X, MessageSquare, Mail, Copy, ChevronDown
} from 'lucide-react';
import dynamic from 'next/dynamic';
import { cn } from '@/lib/utils';
import { DashboardPageContainer } from "@/components/dashboard/DashboardPageContainer";
import PageSkeleton from "@/components/dashboard/ui/PageSkeleton";

const TaskModal = dynamic(() => import('@/components/dashboard/tasks/TaskModal'), { ssr: false });

export default function TasksPage() {
  const supabase = createClient();
  const { organization, loading: orgLoading } = useOrganization();
  const { language } = useLanguage();

  const [loading, setLoading] = useState(true);
  const [tasks, setTasks] = useState<any[]>([]);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [selectedTask, setSelectedTask] = useState<any>(null);
  
  // Filters
  const [statusFilter, setStatusFilter] = useState<string>('all');
  const [priorityFilter, setPriorityFilter] = useState<string>('all');

  // Auto Action Execution Modal (for WhatsApp copy dialog)
  const [whatsappDialog, setWhatsappDialog] = useState<{
    isOpen: boolean;
    text: string;
    phone: string;
  } | null>(null);

  const [actionLoading, setActionLoading] = useState<string | null>(null);

  const localT = {
    es: {
      pageTitle: "Tareas de Seguimiento",
      newTask: "Nueva Tarea",
      kpiUrgent: "Urgentes",
      kpiToday: "Pendientes Hoy",
      kpiWeek: "Esta Semana",
      kpiCompleted: "Completadas",
      filterAll: "Todas",
      filterPending: "Pendientes",
      filterInProgress: "En Proceso",
      filterCompleted: "Completadas",
      filterPriority: "Por Prioridad",
      prioLow: "Baja",
      prioMedium: "Media",
      prioHigh: "Alta",
      prioUrgent: "Urgente",
      typeManual: "Manual",
      typeReminder: "Recordatorio",
      typeFollowUp: "Seguimiento",
      typeAI: "IA",
      createdSystem: "Sistema",
      createdIA: "IA",
      createdManual: "Manual",
      generateAutoBtn: "Generar tareas automáticas",
      execBtn: "Ejecutar",
      completeBtn: "Completar",
      editBtn: "Editar",
      cancelBtn: "Cancelar",
      noTasks: "No hay tareas registradas.",
      searchFilters: "Filtros",
      statusLabel: "Estado",
      priorityLabel: "Prioridad",
      toastAutoGenerated: "{count} tareas nuevas generadas",
      toastCompleted: "Tarea completada con éxito",
      toastCancelled: "Tarea cancelada",
      toastError: "Ocurrió un error inesperado",
      whatsappModalTitle: "Enviar Mensaje de WhatsApp",
      whatsappModalDesc: "Este mensaje debe enviarse manualmente desde tu dispositivo. Copia los detalles a continuación:",
      phoneLabel: "Teléfono",
      messageLabel: "Mensaje",
      copyPhone: "Copiar Teléfono",
      copyMessage: "Copiar Mensaje",
      copied: "¡Copiado!",
      close: "Cerrar"
    },
    en: {
      pageTitle: "Follow-up Tasks",
      newTask: "New Task",
      kpiUrgent: "Urgent",
      kpiToday: "Due Today",
      kpiWeek: "This Week",
      kpiCompleted: "Completed",
      filterAll: "All",
      filterPending: "Pending",
      filterInProgress: "In Progress",
      filterCompleted: "Completed",
      filterPriority: "By Priority",
      prioLow: "Low",
      prioMedium: "Medium",
      prioHigh: "High",
      prioUrgent: "Urgent",
      typeManual: "Manual",
      typeReminder: "Reminder",
      typeFollowUp: "Follow-up",
      typeAI: "AI",
      createdSystem: "System",
      createdIA: "AI",
      createdManual: "Manual",
      generateAutoBtn: "Generate automatic tasks",
      execBtn: "Execute",
      completeBtn: "Complete",
      editBtn: "Edit",
      cancelBtn: "Cancel",
      noTasks: "No tasks found.",
      searchFilters: "Filters",
      statusLabel: "Status",
      priorityLabel: "Priority",
      toastAutoGenerated: "{count} new tasks generated",
      toastCompleted: "Task completed successfully",
      toastCancelled: "Task cancelled",
      toastError: "An unexpected error occurred",
      whatsappModalTitle: "Send WhatsApp Message",
      whatsappModalDesc: "This message must be sent manually from your device. Copy the details below:",
      phoneLabel: "Phone Number",
      messageLabel: "Message Content",
      copyPhone: "Copy Phone",
      copyMessage: "Copy Message",
      copied: "Copied!",
      close: "Close"
    }
  }[language === 'en' ? 'en' : 'es'];

  useEffect(() => {
    fetchTasks();
  }, [organization?.id]);

  // Real-time updates subscription
  useEffect(() => {
    if (!organization?.id) return;

    const channel = supabase
      .channel('tasks-page-changes')
      .on('postgres_changes', { 
        event: '*', 
        schema: 'public', 
        table: 'tasks', 
        filter: `organization_id=eq.${organization.id}` 
      }, () => {
        fetchTasks();
      })
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, [organization?.id, supabase]);

  async function fetchTasks() {
    if (!organization?.id) return;
    setLoading(true);
    try {
      const { data, error } = await supabase
        .from('tasks')
        .select('*')
        .eq('organization_id', organization.id)
        .order('due_date', { ascending: true, nullsFirst: false });

      if (error) throw error;
      setTasks(data || []);
    } catch (err) {
      console.error(err);
      toast.error(localT.toastError);
    } finally {
      setLoading(false);
    }
  }

  // Completing a task
  const handleCompleteTask = async (id: string) => {
    try {
      const { error } = await supabase
        .from('tasks')
        .update({
          status: 'completed',
          completed_at: new Date().toISOString()
        })
        .eq('id', id);

      if (error) throw error;
      toast.success(localT.toastCompleted);
      fetchTasks();
    } catch (err) {
      console.error(err);
      toast.error(localT.toastError);
    }
  };

  // Deleting a task
  const handleDeleteTask = async (id: string) => {
    const confirmDelete = window.confirm(
      language === 'en' ? 'Are you sure you want to delete this task?' : '¿Estás seguro de que deseas eliminar esta tarea?'
    );
    if (!confirmDelete) return;

    try {
      const { error } = await supabase
        .from('tasks')
        .delete()
        .eq('id', id);

      if (error) throw error;
      toast.success(language === 'en' ? 'Task deleted successfully' : 'Tarea eliminada correctamente');
      fetchTasks();
    } catch (err) {
      console.error(err);
      toast.error(localT.toastError);
    }
  };

  // Generating automatic tasks (RPC)
  const handleGenerateAutoTasks = async () => {
    if (!organization?.id) return;
    setActionLoading('generating');
    try {
      const { data, error } = await supabase.rpc('create_followup_tasks', {
        p_org_id: organization.id
      });

      if (error) throw error;
      
      const count = Number(data || 0);
      toast.success(localT.toastAutoGenerated.replace('{count}', String(count)));
      
      if (count > 0) {
        // Prompt 3: Insert system notification in database
        await supabase.from('notifications').insert({
          organization_id: organization.id,
          title: 'Nuevas tareas generadas por el sistema',
          message: `${count} tareas de seguimiento creadas automáticamente`,
          type: 'info',
          link: '/dashboard/tareas',
          read: false
        });
      }
      
      fetchTasks();
    } catch (err) {
      console.error(err);
      toast.error(localT.toastError);
    } finally {
      setActionLoading(null);
    }
  };

  // Execute AI action endpoint (Prompt 4)
  const handleExecuteTask = async (task: any) => {
    setActionLoading(task.id);
    try {
      const res = await fetch('/api/tasks/execute', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          task_id: task.id,
          organization_id: organization?.id
        })
      });
      const result = await res.json();
      
      if (result.error) {
        toast.error(result.error);
        return;
      }
      
      toast.success(
        language === 'en' ? 'Task executed successfully' : 'Tarea ejecutada correctamente'
      );
      
      // If WhatsApp action returned message payload, display manual copy modal
      if (result.action === 'send_whatsapp') {
        setWhatsappDialog({
          isOpen: true,
          text: result.message_text || '',
          phone: result.phone || ''
        });
      }
      
      fetchTasks();
    } catch (err) {
      console.error(err);
      toast.error(localT.toastError);
    } finally {
      setActionLoading(null);
    }
  };

  // KPIs calculations
  const kpis = useMemo(() => {
    const today = new Date();
    const endOfToday = new Date(today.setHours(23, 59, 59, 999));
    
    const weekAhead = new Date();
    weekAhead.setDate(weekAhead.getDate() + 7);
    const endOfWeek = new Date(weekAhead.setHours(23, 59, 59, 999));

    const urgentCount = tasks.filter(t => t.priority === 'urgent' && t.status === 'pending').length;
    
    const todayCount = tasks.filter(t => {
      if (t.status !== 'pending' || !t.due_date) return false;
      const due = new Date(t.due_date);
      return due <= endOfToday;
    }).length;

    const weekCount = tasks.filter(t => {
      if (t.status !== 'pending' || !t.due_date) return false;
      const due = new Date(t.due_date);
      return due <= endOfWeek;
    }).length;

    const completedCount = tasks.filter(t => t.status === 'completed').length;

    return { urgentCount, todayCount, weekCount, completedCount };
  }, [tasks]);

  // Filter tasks
  const filteredTasks = useMemo(() => {
    return tasks.filter(t => {
      const matchStatus = 
        statusFilter === 'all' || 
        (statusFilter === 'pending' && t.status === 'pending') ||
        (statusFilter === 'in_progress' && t.status === 'in_progress') ||
        (statusFilter === 'completed' && t.status === 'completed');

      const matchPriority = 
        priorityFilter === 'all' || 
        t.priority === priorityFilter;

      return matchStatus && matchPriority;
    });
  }, [tasks, statusFilter, priorityFilter]);

  const handleCopyText = (text: string) => {
    navigator.clipboard.writeText(text);
    toast.success(localT.copied);
  };

  const getPriorityDetails = (p: string) => {
    switch (p) {
      case 'urgent':
        return { label: localT.prioUrgent, bg: 'bg-red-500/10 text-red-500 border-red-500/20' };
      case 'high':
        return { label: localT.prioHigh, bg: 'bg-orange-500/10 text-orange-500 border-orange-500/20' };
      case 'medium':
        return { label: localT.prioMedium, bg: 'bg-blue-500/10 text-blue-500 border-blue-500/20' };
      case 'low':
      default:
        return { label: localT.prioLow, bg: 'bg-slate-500/10 text-slate-400 border-slate-500/20' };
    }
  };

  const getTypeLabel = (t: string) => {
    switch (t) {
      case 'reminder': return localT.typeReminder;
      case 'follow_up': return localT.typeFollowUp;
      case 'ai_execute': return localT.typeAI;
      case 'manual':
      default:
        return localT.typeManual;
    }
  };

  const getCreatedByLabel = (c: string) => {
    switch (c) {
      case 'system': return localT.createdSystem;
      case 'ai': return localT.createdIA;
      case 'human':
      default:
        return localT.createdManual;
    }
  };

  if (orgLoading || (loading && organization?.id)) return <PageSkeleton />;

  return (
    <DashboardPageContainer>
      <div className="flex flex-col gap-6 w-full max-w-full text-slate-100 py-2">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-black text-white tracking-tight flex items-center gap-3">
            <CheckSquare className="w-8 h-8 text-[#1B4FD8]" />
            {localT.pageTitle}
          </h1>
        </div>
        <div className="flex flex-wrap items-center gap-3">
          <button
            onClick={handleGenerateAutoTasks}
            disabled={actionLoading === 'generating'}
            className="px-4 py-2.5 bg-blue-500/10 hover:bg-blue-500/20 border border-blue-500/20 text-blue-400 text-xs font-bold rounded-xl transition-all flex items-center gap-2 active:scale-95 disabled:opacity-50"
          >
            <Sparkles className={cn("w-4 h-4", actionLoading === 'generating' && "animate-spin")} />
            {localT.generateAutoBtn}
          </button>

          <button
            onClick={() => {
              setSelectedTask(null);
              setIsModalOpen(true);
            }}
            className="px-5 py-2.5 bg-[#1B4FD8] hover:bg-blue-700 text-white text-xs font-bold rounded-xl transition-all shadow-lg shadow-blue-500/25 flex items-center gap-2 active:scale-95"
          >
            <Plus className="w-4 h-4" />
            {localT.newTask}
          </button>
        </div>
      </div>

      {/* KPIs Grid */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        {[
          { label: localT.kpiUrgent, value: kpis.urgentCount, border: 'border-red-500/20', color: 'text-red-500' },
          { label: localT.kpiToday, value: kpis.todayCount, border: 'border-amber-500/20', color: 'text-amber-500' },
          { label: localT.kpiWeek, value: kpis.weekCount, border: 'border-blue-500/20', color: 'text-blue-500' },
          { label: localT.kpiCompleted, value: kpis.completedCount, border: 'border-emerald-500/20', color: 'text-emerald-500' },
        ].map((item, idx) => (
          <div key={idx} className={cn("bg-[#111F3A] border rounded-2xl p-5 flex flex-col justify-between", item.border)}>
            <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">{item.label}</span>
            <span className={cn("text-2xl md:text-3xl font-black mt-2 leading-none", item.color)}>
              {loading ? (
                <div className="w-12 h-6 bg-slate-800 animate-pulse rounded" />
              ) : (
                item.value
              )}
            </span>
          </div>
        ))}
      </div>

      {/* Filters & Control bar */}
      <div className="bg-[#111F3A] border border-[#1E3A5F] rounded-2xl p-4 flex flex-col md:flex-row items-center justify-between gap-4">
        <div className="flex items-center gap-2 text-slate-400 text-xs font-bold uppercase shrink-0">
          <SlidersHorizontal className="w-4 h-4 text-slate-500" />
          {localT.searchFilters}:
        </div>

        <div className="flex flex-wrap items-center gap-3 w-full justify-start md:justify-end">
          {/* Status buttons */}
          <div className="flex rounded-xl bg-[#0D1B2E] p-1 border border-[#1E3A5F]/50">
            {[
              { id: 'all', label: localT.filterAll },
              { id: 'pending', label: localT.filterPending },
              { id: 'in_progress', label: localT.filterInProgress },
              { id: 'completed', label: localT.filterCompleted }
            ].map(f => (
              <button
                key={f.id}
                onClick={() => setStatusFilter(f.id)}
                className={cn(
                  "px-3 py-1.5 rounded-lg text-xs font-bold transition-all",
                  statusFilter === f.id ? "bg-[#1B4FD8] text-white" : "text-slate-400 hover:text-white"
                )}
              >
                {f.label}
              </button>
            ))}
          </div>

          {/* Priority filter selector */}
          <div className="relative">
            <select
              value={priorityFilter}
              onChange={(e) => setPriorityFilter(e.target.value)}
              className="px-3 py-2 bg-[#0D1B2E] border border-[#1E3A5F]/50 rounded-xl text-xs font-bold text-slate-300 outline-none cursor-pointer appearance-none pr-8"
            >
              <option value="all">{localT.filterPriority}: {language === 'en' ? 'All' : 'Todos'}</option>
              <option value="low">{localT.prioLow}</option>
              <option value="medium">{localT.prioMedium}</option>
              <option value="high">{localT.prioHigh}</option>
              <option value="urgent">{localT.prioUrgent}</option>
            </select>
            <ChevronDown className="absolute right-2.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-slate-500 pointer-events-none" />
          </div>
        </div>
      </div>

      {/* Tasks List */}
      <div className="space-y-3">
        {loading ? (
          Array.from({ length: 3 }).map((_, idx) => (
            <div key={idx} className="h-24 bg-[#111F3A]/50 border border-[#1E3A5F]/30 rounded-2xl animate-pulse" />
          ))
        ) : filteredTasks.length > 0 ? (
          filteredTasks.map((task) => {
            const prio = getPriorityDetails(task.priority);
            const isOverdue = task.due_date && new Date(task.due_date) < new Date() && task.status === 'pending';
            
            return (
              <div 
                key={task.id} 
                className={cn(
                  "bg-[#111F3A] border border-[#1E3A5F]/40 hover:border-[#1E3A5F] rounded-2xl p-4 md:p-5 flex flex-col md:flex-row md:items-center justify-between gap-4 transition-all relative overflow-hidden",
                  task.status === 'completed' && "opacity-60"
                )}
              >
                {/* Visual border for urgency */}
                {task.priority === 'urgent' && task.status === 'pending' && (
                  <div className="absolute left-0 top-0 bottom-0 w-1 bg-red-500" />
                )}

                <div className="flex-1 min-w-0 space-y-2">
                  <div className="flex flex-wrap items-center gap-2">
                    {/* Priority Badge */}
                    <span className={cn("text-[9px] px-2 py-0.5 rounded-full font-black border uppercase tracking-wider", prio.bg)}>
                      {prio.label}
                    </span>

                    {/* Type Badge */}
                    <span className="text-[9px] bg-slate-800 text-slate-300 px-2 py-0.5 rounded-full font-black uppercase tracking-wider">
                      {getTypeLabel(task.type)}
                    </span>

                    {/* Created by badge */}
                    <span className="text-[9px] bg-[#0D1B2E] text-slate-400 px-2 py-0.5 rounded-full font-bold border border-slate-800">
                      {getCreatedByLabel(task.created_by)}
                    </span>
                  </div>

                  <h3 className={cn("text-base font-bold text-white tracking-tight", task.status === 'completed' && "line-through text-slate-400")}>
                    {task.title}
                  </h3>

                  {task.description && (
                    <p className="text-xs text-slate-400 line-clamp-2 max-w-2xl">
                      {task.description}
                    </p>
                  )}

                  <div className="flex flex-wrap items-center gap-4 text-xs mt-1 text-slate-400">
                    {/* Vencimiento */}
                    {task.due_date && (
                      <span className={cn(
                        "flex items-center gap-1.5 font-semibold",
                        isOverdue ? "text-red-400" : "text-slate-400"
                      )}>
                        <Clock className="w-3.5 h-3.5" />
                        {new Date(task.due_date).toLocaleDateString(language === 'en' ? 'en-US' : 'es-ES', { 
                          day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' 
                        })}
                      </span>
                    )}

                    {/* Vinculado a Chip */}
                    {task.related_type && task.related_name && (
                      <span className="inline-flex items-center gap-1.5 px-2 py-0.5 bg-blue-500/10 text-blue-400 border border-blue-500/20 rounded-md text-[11px] font-bold">
                        <Link2 className="w-3 h-3" />
                        {task.related_type.toUpperCase()}: {task.related_name}
                      </span>
                    )}
                  </div>
                </div>

                {/* Actions Section */}
                <div className="flex flex-wrap items-center gap-2 shrink-0 border-t border-[#1E3A5F]/20 md:border-none pt-3 md:pt-0">
                  {/* Completar */}
                  {task.status === 'pending' && (
                    <button
                      onClick={() => handleCompleteTask(task.id)}
                      className="p-2 bg-emerald-500/10 hover:bg-emerald-500/20 text-emerald-400 hover:text-white rounded-xl transition-all flex items-center gap-1.5 text-xs font-bold border border-emerald-500/20 active:scale-95"
                      title={localT.completeBtn}
                    >
                      <Check className="w-4 h-4" />
                      <span className="hidden sm:inline">{localT.completeBtn}</span>
                    </button>
                  )}

                  {/* AI Execute action (send WhatsApp copy message or send Resend email) */}
                  {task.auto_action && !task.auto_executed_at && task.status === 'pending' && (
                    <button
                      onClick={() => handleExecuteTask(task)}
                      disabled={actionLoading === task.id}
                      className="p-2 bg-blue-600 hover:bg-blue-700 text-white rounded-xl transition-all flex items-center gap-1.5 text-xs font-bold shadow-lg shadow-blue-500/20 active:scale-95 disabled:opacity-50"
                      title={localT.execBtn}
                    >
                      {actionLoading === task.id ? (
                        <RefreshCw className="w-4 h-4 animate-spin" />
                      ) : task.auto_action === 'send_whatsapp' ? (
                        <MessageSquare className="w-4 h-4" />
                      ) : (
                        <Mail className="w-4 h-4" />
                      )}
                      <span>{localT.execBtn}</span>
                    </button>
                  )}

                  {/* Editar */}
                  {task.status === 'pending' && (
                    <button
                      onClick={() => {
                        setSelectedTask(task);
                        setIsModalOpen(true);
                      }}
                      className="p-2 hover:bg-slate-800 text-slate-300 hover:text-white rounded-xl transition-all border border-transparent hover:border-slate-800"
                      title={localT.editBtn}
                    >
                      <Edit className="w-4 h-4" />
                    </button>
                  )}

                  {/* Borrar */}
                  <button
                    onClick={() => handleDeleteTask(task.id)}
                    className="p-2 hover:bg-red-500/10 text-slate-400 hover:text-red-400 rounded-xl transition-all border border-transparent hover:border-red-500/10"
                    title={language === 'en' ? 'Delete' : 'Eliminar'}
                  >
                    <Trash2 className="w-4 h-4" />
                  </button>
                </div>
              </div>
            );
          })
        ) : (
          <div className="flex flex-col items-center justify-center p-12 text-center border-2 border-dashed border-[#1E3A5F]/40 rounded-2xl">
            <CheckSquare className="w-12 h-12 text-slate-600 mb-3" />
            <p className="text-slate-400 text-sm">{localT.noTasks}</p>
          </div>
        )}
      </div>

      {/* Task Creation/Editing Modal */}
      <TaskModal
        isOpen={isModalOpen}
        onClose={() => {
          setIsModalOpen(false);
          setSelectedTask(null);
        }}
        onSuccess={fetchTasks}
        editTask={selectedTask}
      />

      {/* WhatsApp Message Copy Dialogue Modal */}
      {whatsappDialog?.isOpen && (
        <div className="fixed inset-0 z-[10000] flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm animate-in fade-in duration-200">
          <div className="bg-[#111F3A] w-full max-w-md rounded-2xl shadow-2xl border border-[#1E3A5F] overflow-hidden flex flex-col">
            <div className="px-5 py-4 border-b border-[#1E3A5F] flex items-center justify-between">
              <h3 className="text-base font-bold text-white flex items-center gap-2">
                <MessageSquare className="w-5 h-5 text-emerald-500" />
                {localT.whatsappModalTitle}
              </h3>
              <button 
                onClick={() => setWhatsappDialog(null)}
                className="p-1 hover:bg-slate-800 rounded-full transition-colors"
              >
                <X className="w-4 h-4 text-slate-400" />
              </button>
            </div>
            
            <div className="p-5 space-y-4">
              <p className="text-xs text-slate-400 leading-relaxed">
                {localT.whatsappModalDesc}
              </p>

              {/* Teléfono */}
              {whatsappDialog.phone ? (
                <div className="space-y-1">
                  <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{localT.phoneLabel}</span>
                  <div className="flex items-center justify-between p-3 bg-[#0D1B2E] border border-[#1E3A5F] rounded-xl">
                    <span className="text-sm font-semibold text-white">{whatsappDialog.phone}</span>
                    <button
                      onClick={() => handleCopyText(whatsappDialog.phone)}
                      className="p-1.5 hover:bg-slate-800 text-[#1B4FD8] hover:text-blue-400 rounded transition-colors"
                      title={localT.copyPhone}
                    >
                      <Copy className="w-4 h-4" />
                    </button>
                  </div>
                </div>
              ) : (
                <div className="p-3 bg-red-500/10 border border-red-500/20 text-red-400 text-xs rounded-xl flex items-center gap-2">
                  <AlertTriangle className="w-4 h-4 shrink-0" />
                  <span>{language === 'en' ? 'No phone number associated with this contact.' : 'No hay número de teléfono asociado a este contacto.'}</span>
                </div>
              )}

              {/* Mensaje */}
              <div className="space-y-1">
                <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{localT.messageLabel}</span>
                <div className="relative p-3 bg-[#0D1B2E] border border-[#1E3A5F] rounded-xl flex flex-col justify-between gap-3">
                  <p className="text-xs text-slate-200 whitespace-pre-line leading-relaxed max-h-[150px] overflow-y-auto custom-scrollbar">
                    {whatsappDialog.text}
                  </p>
                  <button
                    onClick={() => handleCopyText(whatsappDialog.text)}
                    className="self-end px-3 py-1.5 bg-[#1B4FD8] hover:bg-blue-700 text-white text-[10px] font-bold rounded-lg transition-colors flex items-center gap-1"
                  >
                    <Copy className="w-3.5 h-3.5" />
                    {localT.copyMessage}
                  </button>
                </div>
              </div>
            </div>

            <div className="px-5 py-4 border-t border-[#1E3A5F] bg-slate-900/30 flex justify-end">
              <button
                onClick={() => setWhatsappDialog(null)}
                className="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-bold rounded-xl transition-colors"
              >
                {localT.close}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
    </DashboardPageContainer>
  );
}
